comment: None
total_steps: 1e6
n_envs: 1
render: False
device: "cuda"
is_wandb: True
project: ${env.env_id}_irdd

env:
  r_gamma: 0.99
  test_end_id: ${env.env_id}

gen:
  model: PPO2
  lr: 3e-4
  batch_size: 64
  target_kl: 0.1
  n_epochs: 20
  ent_coef: 1e-2

disc:
  demo_batch_size: 2048
  gen_replay_buffer_capacity: 4096
  n_disc_updates_per_round: 10
  lr: 3e-4
  hid_size: 16

defaults:
  - env: serving
