# @package _global_
comment: None
total_steps: 2e5
n_envs: 16
render: False
device: "cuda"
is_wandb: True
project: ${env.env_id}_irdd

allow_variable_horizon: True
env:
  env_id: "CartPole-v1"
  r_gamma: 0.99

disc:
  demo_batch_size: 1024
  gen_replay_buffer_capacity: 2048
  n_disc_updates_per_round: 4
  lr: 3e-4
  hid_size: 32
  normalize: None
  coef: [1.0, 1.0, 0.0]
  reg_coef: [1.0, 1.0, 0.0]
gen:
  model: PPO2
  lr: 3e-4
  batch_size: 64 
  target_kl: 0.1
  n_epochs: 20
  ent_coef: 1e-4
  # n_steps: ${disc.gen_replay_buffer_capacity//n_envs}
  n_steps: 100
