# @package _global_
comment: None
total_steps: 10e6
n_envs: 16
render: False
device: "cuda"
is_wandb: True
project: ${env.env_id}_irdd

env:
  env_id: "Serving-v1"
  r_gamma: 0.99

disc:
  demo_batch_size: 3200
  gen_replay_buffer_capacity: 6400
  n_disc_updates_per_round: 40
  lr: 3e-4
  hid_size: 16
  normalize: None
  reward_net_opt: None
  primary_net_opt: Adam
  constraint_net_opt: Adam
  coef: [1.0, 0.5, 0.5]
  clip_range: 0.2
  
gen:
  model: PPO2
  lr: 3e-4
  batch_size: 64
  target_kl: 0.1
  n_epochs: 30
  ent_coef: 1e-4
  # n_steps: ${disc.gen_replay_buffer_capacity//n_envs}
  n_steps: 100
